program := strlen2 strlen3 strpbrk strspn count my_strlen \
	   my_strcpy my_strcat my_strcpy_end my_strrchr \
	   my_strnchr count_chars palindrome count_the \
	   encrypt dollars

.PHONY: all clean
all: $(program)

clean:
	@rm -f $(program) *.o *.s
