PROGRAMS := string1 string2 string3 string4 string5 string6 string7 string8 \
	string9 string10 string11 string12
OBJECTS =
ASSEMBLE :=
CFLAGS = -g -Wall
LDFLAGS =

.PHONY: all clean
all: $(PROGRAMS) $(OBJECTS) $(ASSEMBLE)

clean:
	@rm -f $(PROGRAMS) $(ASSEMBLE)
