PROGRAMS := ptr1 ptr2 ptr3 ptr4 ptr5 pass_by_value pass_by_reference ptr6 \
	ptr10
OBJECTS =
ASSEMBLE :=
CFLAGS = -g -Wall
LDFLAGS =

.PHONY: all clean
all: $(PROGRAMS) $(OBJECTS) $(ASSEMBLE)

clean:
	@rm -f $(PROGRAMS) $(ASSEMBLE)
