PROGRAMS := struct1 struct2 struct3 struct4 struct5 struct6 struct7 struct8 \
	struct9 struct10 struct11 struct12 struct13 struct14 struct16 struct17
OBJECTS =
ASSEMBLE :=
CFLAGS = -g -Wall
LDFLAGS =

.PHONY: all clean
all: $(PROGRAMS) $(OBJECTS) $(ASSEMBLE)

clean:
	@rm -f $(PROGRAMS) $(ASSEMBLE)
