PROGRAMS := fibo copystructs copystructs2 automem memmove arithmetic pointer_arithmetic1 \
	    pointer_arithmetic2
OBJECTS =
CFLAGS = -g -Wall -O3
LDFLAGS = 

.PHONY: all clean
all: $(PROGRAMS) $(OBJECTS)

clean:
	@rm -f $(PROGRAMS) *.o
