PROGRAMS := multidim1 multidim2 multidim3 multidim4 multidim5 multidim6 \
	multidim7 multidim8 multidim9 multidim10 multidim11 multidim12
OBJECTS =
ASSEMBLE :=
CFLAGS = -g -Wall
LDFLAGS =

.PHONY: all clean
all: $(PROGRAMS) $(OBJECTS) $(ASSEMBLE)

clean:
	@rm -f $(PROGRAMS) $(ASSEMBLE)
